### ISSUE TITLE
context.rank() vs comm.rank()

### ISSUE THREAD

**Issue by angainor** [GridTools/GHEX#51]
We can currently obtain (MPI) rank and size from both the context, and the communicator. Will the communicator ever have a different value of those variables? Should we only expose this through the context? When I see both, I don't know which one to use, and whether there is a difference.

**Comment by boeschf** [comment]
there should be no difference, both return the same values

**Comment by angainor** [comment]
@boeschf I know. my point is that maybe we should only have one or the other.

**Comment by boeschf** [comment]
Maybe, but I am not convinced. I like the fact that you can query rank and size of your environment from a serial region and/or without actually making a communicator.

**Comment by angainor** [comment]
@boeschf That is an argument for leaving it in the context. Then why do we also need it in the communicator?

**Comment by boeschf** [comment]
basically because it is convenient

**Comment by angainor** [comment]
Sure. I don't have strong feeling about it. Just found it a bit confusing. Theoretically, if you have a MT environment and a communicator per thread, you would expect it to have a different rank per thread. But we can also keep it this way.

**Comment by boeschf** [comment]
For that we have the `thread_token` - it gives you a thread id.
